tagFormat: ${version}

plugins:
  - @semantic-release/commit-analyzer
  - @semantic-release/release-notes-generator
  - - @semantic-release/changelog
    - changelogFile: docs/CHANGELOG.md
  - - @semantic-release/git
    - message: "release: 🚀 ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
      assets: [docs/CHANGELOG.md]
  - - @semantic-release/exec
    - publishCmd: './gradlew clean assemble'
  - - @semantic-release/github
    - assets:
        - path: "build/libs/slugger-${nextRelease.version}.jar"
          label: Slugger Jar
        - path: "build/libs/slugger-${nextRelease.version}-javadoc.jar"
          label: Slugger Javadoc Jar
        - path: "build/libs/slugger-${nextRelease.version}-sources.jar"
          label: Slugger Sources Jar
