language: java
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13

stages:
  - name: test
  - name: release
    if: branch =~ /^(master|hotfix-.*)$/
  - name: publish
    if: (tag =~ ^release) AND (branch =~ /^(master|hotfix-.*)$/)


jobs:
  include:
    - name: "Unit Tests"
      stage: test
      script: ./gradlew test
    - name: "Cucumber Tests"
      stage: test
      script: ./gradlew cucumber
    - name: "Tag Release"
      stage: release
      jdk: openjdk11
      script: skip
      deploy:
        provider: script
        script: ./gradlew final
    - name: "GitHub Release"
      stage: publish
      jdk: openjdk11
      script: assemble
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        file_glob: true
        file: build/libs/*
