name: Release

on:
  push:
    branches: [ master ]

jobs:
  release:
    name: Release Slugger
    steps:
      - uses: brpaz/action-semantic-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}