name: Release

on:
  push:
    branches: [ master ]

jobs:
  release:
    name: Release Slugger
    runs-on: ubuntu-latest
    steps:
      - uses: brpaz/action-semantic-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GITHUB_URL: github.com/eddarmitage/Slugger.git